-- DROP FUNCTIONS AND PROCEDURES FIRST
DROP FUNCTION IF EXISTS get_user_notifications(INT);
DROP FUNCTION IF EXISTS get_user_claim_requests(INT);
DROP FUNCTION IF EXISTS get_user_return_requests(INT);
DROP FUNCTION IF EXISTS user_login(VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS user_signup(VARCHAR, VARCHAR, VARCHAR, NUMERIC, BIGINT);
DROP FUNCTION IF EXISTS get_locations();
DROP FUNCTION IF EXISTS get_tags();

DROP PROCEDURE IF EXISTS create_claim_request_found(INT, INT, TEXT, TEXT[]);
DROP PROCEDURE IF EXISTS create_return_request_lost(INT, INT, TEXT, TEXT[]);
DROP FUNCTION IF EXISTS user_login(VARCHAR, TEXT);
DROP FUNCTION IF EXISTS user_signup(VARCHAR, BIGINT, VARCHAR, NUMERIC, TEXT);
DROP FUNCTION IF EXISTS get_locations();
DROP FUNCTION IF EXISTS get_tags();

DROP PROCEDURE IF EXISTS create_claim_request_found(INT, INT, TEXT);
DROP PROCEDURE IF EXISTS create_claim_request_lost(INT, INT, TEXT);
DROP PROCEDURE IF EXISTS delete_notification(INT);
DROP PROCEDURE IF EXISTS mark_notification_as_read(INT, INT);
DROP PROCEDURE IF EXISTS archive_lost_report(INT);
DROP PROCEDURE IF EXISTS archive_found_report(INT);
DROP PROCEDURE IF EXISTS create_lost_report(INT, INT, VARCHAR, TEXT, TIMESTAMP, INT[], TEXT[]);
DROP PROCEDURE IF EXISTS create_found_report(INT, INT, VARCHAR, TEXT, TIMESTAMP, INT[], TEXT[]);

-- DROP VIEWS
DROP VIEW IF EXISTS vw_lost_reports;
DROP VIEW IF EXISTS vw_found_reports;

-- DROP TABLES (reverse dependency order)
DROP TABLE IF EXISTS Found_Report_Tags;
DROP TABLE IF EXISTS Lost_Report_Tags;

DROP TABLE IF EXISTS Return_Request_Images;
DROP TABLE IF EXISTS Claim_Request_Images;
DROP TABLE IF EXISTS Found_Report_Images;
DROP TABLE IF EXISTS Lost_Report_Images;

DROP TABLE IF EXISTS Return_Request;
DROP TABLE IF EXISTS Claim_Request;

DROP TABLE IF EXISTS Found_Report;
DROP TABLE IF EXISTS Lost_Report;

DROP TABLE IF EXISTS Location;
DROP TABLE IF EXISTS Notification;
-- DROP TABLE IF EXISTS Auth;
-- DROP TABLE IF EXISTS Users;

DROP TABLE IF EXISTS Tags;

-- DROP ENUM TYPES
DROP TYPE IF EXISTS request_status_enum;
DROP TYPE IF EXISTS report_status_enum;
DROP TYPE IF EXISTS gender_enum;
